### ISSUE TITLE
only to client users

### ISSUE THREAD

**Issue by siurana-lin** [MegaPiggy/LethalCompanyBuyableShotgun#1]
The mod seems to have to be installed by host, I guess as the client side also has a single purchase feature, and it is possible to install the mod without a host

**Comment by MegaPiggy** [comment]
I'm not sure what you mean by this. You need every player to have the mod or it won't work.

**Comment by siurana-lin** [comment]
I mean I tried to buy Shotgun after joining another player's game, but the rocket I sent wouldn't open it
