### ISSUE TITLE
Mod broken

### ISSUE THREAD

**Issue by JADundee** [MegaPiggy/LethalCompanyBuyableShotgun#11]
### What Happened?

Comes up as error with a box model, the shell mod is also broken 

### Game version

49

### Mods

```Markdown
018d9b6f-5809-9d4d-f88d-b0e30ce903e7
```

**Comment by MegaPiggy** [comment]
Need to install LC_API. One of your mods there requires it (i don't know which) and because it can't find it that breaks the loading of that mod and by extension my mod.
