### ISSUE TITLE
Shotgun not appearing 

### ISSUE THREAD

**Issue by mommyhuntress** [MegaPiggy/LethalCompanyBuyableShotgun#13]
### What Happened?

the host can see the shotgun but anyone else cant see it or hear it. so nobody can use it :(

### Game version

v49

### Mods

```Markdown
018e0854-f245-ae91-faf4-cc24be038c2a
```

**Comment by c0bbo** [comment]
can confirm - this is happening to me as well

**Comment by MegaPiggy** [comment]
yeah I've been getting influx of reports about this recently. I'll be looking into it and trying to fix in a few hours.

**Comment by MegaPiggy** [comment]
thanks for sharing the profile code. makes it a bit easier for me.

**Comment by MegaPiggy** [comment]
It should be fixed now in 1.1.0 update

**Comment by mommyhuntress** [comment]
Thank you! 😇Sent from my iPhoneOn Mar 5, 2024, at 4:30 PM, Noah Pilarski ***@***.***> wrote:﻿
It should be fixed now in 1.1.0 update
