### ISSUE TITLE
[Bug]: Shotgun + ammo purchased from the store disappears.

### ISSUE THREAD

**Issue by pil0lo** [MegaPiggy/LethalCompanyBuyableShotgun#18]
### What Happened?

Every time I leave and come back, the shotgun and several bullets keep disappearing.

### What was supposed to happen?

Every time I leave and come back, the shotgun and several bullets keep disappearing.

### Game version

V49

### Mods

```Markdown
BuyableShotgun v1.1.0 by MegaPiggy
BuyableShotgunShells v1.1.0 by MegaPiggy
SaveMyShotty v1.0.1 by Bombers_Team
```

**Comment by Zouizoui78** [comment]
Same here. I switched to [this mod](https://thunderstore.io/c/lethal-company/p/Bombers_Team/SaveMyShotty/) in which the bug is fixed.

**Comment by VirusTLNR** [comment]
> Same here. I switched to [this mod](https://thunderstore.io/c/lethal-company/p/Bombers_Team/SaveMyShotty/) in which the bug is fixed.

only host can see the shotguns though, so doesnt work in multiplayer.
