### ISSUE TITLE
HOW TO CONFIGURE PRICE?? 

### ISSUE THREAD

**Issue by Jackdadan** [MegaPiggy/LethalCompanyBuyableShotgun#19]
### What Happened?

I can’t see any instructions on how to configure the price for the shotgun can you please help? Thanks 

### What was supposed to happen?

clarkjackpersonal@gmail.com 

if you can please send instructions thank you 

### Game version

Vnewest 

### Mods

```Markdown
Buyableshotgun
```

**Comment by abdiascavada** [comment]
Same, i want to configure the price but no idea how to do it

**Comment by Scarefact** [comment]
It's in the config.

**Comment by Jackdadan** [comment]
@Scarefact how do you change it? No instructions on how to change it

**Comment by Scarefact** [comment]
> @Scarefact how do you change it? No instructions on how to change it
![Untitled](https://github.com/MegaPiggy/LethalCompanyBuyableShotgun/assets/162903166/d7369600-1435-4078-b6be-d253f6f3523d)
