### ISSUE TITLE
[Bug]: ESC and Tab not working 

### ISSUE THREAD

**Issue by silverq1233** [MegaPiggy/LethalCompanyBuyableShotgun#3]
### What Happened?

After installing the mod, Tab and ESC do not work

### Game version

v45

### Mods

```Markdown
Buyable Shotgun
Evaisa-HookGenPatcher
Evaisa-LethalLib
```

**Comment by MegaPiggy** [comment]
You must be playing on latest version (v49) for this mod to work! v45 is the old version.
