### ISSUE TITLE
[Bug]: Shotgun is a white block and removes all functions

### ISSUE THREAD

**Issue by LycanWolfUK** [MegaPiggy/LethalCompanyBuyableShotgun#4]
### What Happened?

whenever I pick up the shotgun, it goes into the weapon slot but also my main inventory and has a white box in there, it also prevents me from picking anything else up or interacting with anything, I've bought a new one to test it, same result, I've downgraded the previous versions and its the same there

I have disabled the weapon slot mod in case this was causing it to no avail, unsure of what to do atm

### What was supposed to happen?

picked up like normal either into the main inventory or reserved weapon slot

### Game version

v47

### Mods

```Markdown
018d3754-97ce-0892-7ae3-2fd90240d06e
```

**Comment by MegaPiggy** [comment]
I figured out the issue. Thanks for putting the profile code. 

Before:
![Before](https://github.com/MegaPiggy/LethalCompanyBuyableShotgun/assets/34462599/1f1d2944-ea0c-4df8-ac93-370f3e2a8d8f)

After:
![After](https://github.com/MegaPiggy/LethalCompanyBuyableShotgun/assets/34462599/6d90a178-cf56-46cf-8620-d5b9cf9410c9)

**Comment by LycanWolfUK** [comment]
It seemed to conflict with the Brutal Company Minus mod, since disabling, its works fine now

**Comment by MegaPiggy** [comment]
Well it should work fine together now with latest update that I just published on thunderstore.
