### ISSUE TITLE
Buyable Problem

### ISSUE THREAD

**Issue by Maximum192** [MegaPiggy/LethalCompanyBuyableShotgun#5]
### What Happened?

Buyable Shotgun doesnt show up on the terminal.

### Game version

latest

**Comment by MegaPiggy** [comment]
I can't attempt to fix a problem without knowing what mods you had installed.
Could you provide a list or a mod manager profile code?

**Comment by Maximum192** [comment]
slow down on saying some code and stuff cause I'm not a dev coder or somethin
just to let u know 

I had the mod and tried to test it for some reason I dont seem to see shotgun on the store, I tried removed/less some of the mod still notin

I checked the command thing for lethal company theres no error in it.

also check mod list that the buyableshotgun is detect and the config but didnt show anything in game.

I hope this understand you

**Comment by MegaPiggy** [comment]
I didn't say anything about code
I just asked what mods you had with this one

**Comment by Maximum192** [comment]
to be honest I have a lot of mod [like over 60+] so I cant explain every mod I have but I tried hide all of my mods and left the buyableshotgun.dll and buyableshells.dll so I tested it, hells is in the terminal store but shotgun is not shown

**Comment by Maximum192** [comment]
ok update i got an error on the command thing and it said the buyableshotgun doesnt work HookGenPatcher needs update to work

but i have the latest update HookGenPatcher
